name: Bolão - Mensagem Bom Dia

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch: 

jobs:
  mandar-bom-dia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Mandar mensagem de bom dia
        env:
          EVOLUTION_URL: ${{ secrets.EVOLUTION_URL }}
          EVOLUTION_APIKEY: ${{ secrets.EVOLUTION_APIKEY }}
          EVOLUTION_PHONE_ANUNCIOS: ${{ secrets.EVOLUTION_PHONE_ANUNCIOS }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID:           ${{ secrets.SHEET_ID }}
          DATAS:           ${{ secrets.DATAS }}
        run: python -m scripts.send_messages.send_bom_dia